website/__init__.py
from flask import Flask, render_template_string, request
from flask_flatpages import FlatPages
from flask_flatpages.utils import pygmented_markdown
from flask.ext.images import Images

def jinja_renderer(text):
  prerendered_body = render_template_string(text)
  return pygmented_markdown(prerendered_body)

app = Flask(__name__)

# Default Values for config
app.config['SECTION_MAX_LINKS'] = 10
app.config['FLATPAGES_HTML_RENDERE'] = jinja_renderer
app.config.from_object('config')
pages = FlatPages(app)
images = Images(app)

from website.views import general
from website.views import pages

app.register_blueprint(general.mod)
app.register_blueprint(pages.mod)

@app.context_processor
def context_data():
  def is_active(endpoint=None, section=None, noclass=False):
    rtn = ""
    if noclass:
      rtn = 'active'
    else:
      rtn = 'class=active'
    if endpoint and section:
      if 'section' in request.view_args:
        if request.url_rule.endpoint == endpoint and request.view_args['section'] == section:
          return rtn
    elif endpoint:
      return rtn if request.url_rule.endpoint == endpoint else ''
    elif section:
      if 'section' in request.view_args:
        return rtn if request.view_args['section'] == section else ''
    return ''
  return dict(is_active=is_active,
              debug=app.debug)

website/views/general.py
from website import app
from flask import Blueprint, render_template, session, redirect, url_for, \
        request, abort

mod = Blueprint('general', __name__)


@mod.route('/about')
def about(name=None):
  return render_template('general/about.html', name=name)

@mod.route('/what-we-believe')
def believe(name=None):
  return render_template('general/believe.html', name=name)

@mod.route('/calendar')
def calendar(name=None):
  return render_template('general/calendar.html', name=name)

@mod.route('/contact')
def contact(name=None):
  return render_template('general/contact.html', name=name)

@mod.route('/pictures')
def pictures (name=None):
  return render_template('general/pictures.html',name=name)

@mod.route('/team')
def team(name=None):
  return render_template('general/team.html', name=name)

website/views/pages.py
from datetime import date, datetime
from website import app
from flask import Blueprint, render_template, session, redirect, url_for, \
        request, abort
from flask_flatpages import FlatPages
from random import sample
import os

mod = Blueprint('pages', __name__)
pages = FlatPages(app)

def get_pages(pages, offset=None, limit=None, section=None, year=None, before=None, after=None):
  """ Retrieves pages that match specific criteria
  """
  things = list(pages)
  # Assign section if one is not set in the page
  for thing in things:
    if not thing.meta.get('section'):
      thing.meta['section'] = thing.path.split('/')[0]
  # filter unpublished
  if not app.debug:
    things = [p for p in things if p.meta.get('published') is True]
  # filter section
  if section:
    things = [p for p in things if p.meta.get('section') == section]
  # filter year
  if year:
    things = [p for p in things if p.meta.get('date').year == year]
  if before:
    things = [p for p in things if p.meta.get('date') < before]
  if after:
    things = [p for p in things if p.meta.get('date') > after]
  # sort what's left by date
  things = sorted(things, reverse=True, key=lambda p: p.meta.get('date', date.today()))
  # assign prev/next in series
  for i, thing in enumerate(things):
    if i != 0:
      if section and things[i - 1].meta.get('section') == section:
        thing.next = things[i - 1]
    if i != len(things) - 1:
      if section and things[i +1].meta.get('section') == section:
        thing.prev = things[i +1]
  # offset and limit
  if offset and limit:
    return things[offset:limit]
  elif limit:
    return things[:limit]
  elif offset:
    return things[offset:]
  else:
    return things
  
def get_years(pages):
  years = list(set([page.meta.get('date').year for page in pages]))
  years.reverse()
  return years

def section_exists(section):
  return not len(get_pages(pages, section=section)) == 0

@mod.route('/<path:path>/')
def page(path):
  section = path.split('/')[0]
  page = pages.get_or_404(path)
  # ensure an accurate "section" meta is available
  page.meta['section'] = page.meta.get('section', section)
  # show all pages in debug, but hide unpublished in production
  if not app.debug and not page.meta.get('published', False):
    abort(404)
  template = page.meta.get('template', '%s/page.html' % section)
  rtn_images = []
  if os.path.isdir(os.path.join(app.static_folder, 'images', path)):
    raw_images = os.listdir(os.path.join(app.static_folder, 'images', path))
    if len(raw_images) > 3:
      choices = sample(raw_images, 3)
    else:
      choices = raw_images
    for raw_image in choices:
      # Flask-Images already knows to look in the static folder, so only include the rest
      rtn_images.append(os.path.join('images', path, raw_image))
  return render_template(template, page=page, section=section, images=rtn_images)

@mod.route('/<string:section>/')
def section(section):
  if not section_exists(section):
    abort(404)
  template = '%s/index.html' % section
  things = get_pages(pages, limit=app.config['SECTION_MAX_LINKS'], section=section)
  years = get_years(get_pages(pages, section=section))
  return render_template(template, pages=things, section=section, years=years)

@mod.route('/<string:section>/upcoming/')
def section_upcoming(section):
  if not section_exists(section):
    abort(404)
  template = '%s/upcoming.html' % section
  things = get_pages(pages, section=section, after=date.today())
  years = get_years(get_pages(pages, section=section))
  return render_template(template, pages=things, section=section, years=years)

@mod.route('/<string:section>/past/')
def section_past(section):
  if not section_exists(section):
    abort(404)
  template = '%s/past.html' % section
  things = get_pages(pages, section=section, before=date.today())
  years = get_years(get_pages(pages, section=section))
  return render_template(template, pages=things, section=section, years=years)

@mod.route('/<string:section>/<int:year>/')
def section_archives_year(section, year):
  if not section_exists(section):
    abort(404)
  template = '%s/archives.html' % section
  years = get_years(get_pages(pages, section=section))
  things = get_pages(pages, section=section, year=year)
  return render_template(template, pages=things, section=section, years=years, year=year)

@mod.route('/')
def all_pages():
  template = 'general/index.html'
  things = get_pages(pages, limit=app.config['SECTION_MAX_LINKS'])
  years = get_years(get_pages(pages))
  return render_template(template, pages=things, years=years)

website/templates/_list.html
<div class="row">
    {%- for page in pages %}
    <div class="well {% if not page.published %}unpublished{% endif %}">
        <h2>
            <a href="{{ url_for('pages.page', path=page.path) }}">{{ page.title }}</a>
            | <time datetime="{{ page.date }}">{{ page.date }}</time>
        </h2>
        <q itemprop="description">
            {%- if page.meta.summary and page.meta.summary|striptags|trim %}
                {{- page.summary|trim }}
            {%- elif page.html|striptags|trim -%}
                {{- page.html|striptags|trim|truncate(135) }}
            {%- endif -%}
        </q>
        <hr>
    </div>
    {%- else %}
      <div>No pages (yet?)</div>
    {%- endfor %}
</div>

website/templates/base.html
<!DOCTYPE html>
<html lang='en'>

  <head>

    <!-- Pull in all the CSS and JS scripts -->
    {% include 'layouts/head.html' with context %}

    <!-- Allow inline CSS from child page -->
    <style>
      {% block style %}{% endblock style %}
    </style>

    <!-- Pull title from each page if it exists -->
    <title>
      {% block title %}Ramblings{% endblock title %}
    </title> 

  </head>

  <body>

  <!-- Get the <header> data -->
  {% include 'layouts/header.html' %}

  <!-- Main DIV -->
  <div class="container-fluid text-center">
    <div class="row">

      <!-- Pull in the Progress bars and Left Column -->
      {% include 'layouts/left_col.html' %} 

      <!-- Central Content DIV -->
      <div class="col-sm-7 text-left" >
        <!-- Central ALERT Text -->
        {% block alert %}{% endblock alert %}

        <!-- CONTENT PAGE TITLE -->
        {% if self.pagetitle() %}
        <div class="row">
          <div class="col-sm-12 text-center">
            <h1>{% block pagetitle %}{% endblock pagetitle %}</h1> 
          </div>
        </div>
        {% endif %}

        <!-- Get the Main Content -->
        {% block content %}
          Default content
        {% endblock content %}

        <!-- Pagination -->
        {% include 'layouts/central-pagination.html' %}

      <!-- END Central Content DIV -->
      </div>
   
      <!-- Social Media / Right Column --> 
      {% include 'layouts/right_col.html' %}

    <!-- END Main DIV -->
    </div>
  </div>

  <!-- get the <footer> -->
  {% include 'layouts/footer.html' %} 

  </body>
</html>

website/templates/blog/archives.html
{% extends 'blog/base.html' %}
{% block title %}Blog Archives{% endblock %}
{% block content %}
<h3>Events in {{ year }}</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item" href="{{ url_for('pages.section', section=section) }}">Back to {{ section }}</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}
{% endblock %}

website/templates/blog/base.html
{% extends 'base.html' %}

{% block page_title %}Event{% endblock page_title %}
{% block title %}Event{% endblock title %}
{% block section %}events{% endblock section %}

website/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Ramblings of a mad man{% endblock %}
{% block content %}
<h3> Latest Posts</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item disabled" href="#">Browse {{ section }} archives</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}

{% endblock %}

website/templates/blog/page.html
{% extends 'blog/base.html' %}

{% if page.title %}
  {% block title %}
    {{ page.title }}
  {% endblock title %}
{% endif %}

{% if page.alert %}
  {% block alert %}
    {{ page.alert }}
  {% endblock alert %}
{% endif %}

{% if page.pagetitle %}
  {% block pagetitle %}
    {% if page.date %}
      {{ page.pagetitle }} - {{ page.date }}
    {% else %}
      {{ page.pagetitle }}
    {% endif %}
  {% endblock pagetitle %}
{% endif %}

<!-- Get the Main Content -->
{% block content %}
<div class="row well">
  {{  page }}
</div>
{% if images %}
<div class="row text-center">
{% for image in images %}
  <div class="col-sm-4 text-center">
    <img class="img-responsive well" src="{{ url_for('images.fit', filename=image, width=400) }}" />
  </div>
{% endfor %}
</div>
{% endif %}
  {% if page.prev -%}
  <a class="prev" href="{{ url_for("pages.page", path=page.prev.path) }}">&lt;&lt; {{ page.prev.title }} - {{page.prev.date}}</a>
  {%- endif %}
  {% if page.prev and page.next %} | {% endif %}
  {% if page.next -%}
  <a class="next" href="{{ url_for("pages.page", path=page.next.path) }}">{{ page.next.title }} - {{page.next.date}} &gt;&gt;</a>
  {%- endif %} 
{% endblock content %}

website/templates/general/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block pagetitle %}Reverb{% endblock %}
{% block content %}
<h3>Student Ministry</h3>
<p>Colossians 1:10 "so that you will walk in a manner worth of the Lord, to please Him in all respects, bearing fruit in every good 
work and increasing in the knowledge of God;"
   <h3>Senior High Ministry</h3>
   <p>Galatians 2:20 "I have been crucified with Christ; and it is no longer I who live, but Christ lives in me; and the life 
which I now live in the flesh I live by faith in the Son of God, who loved me and gave Himself up for me."</p>    
<h3>Vision</h3>
   <p>Amplify life. Exemplify Christ</p>
   <h3>Mission</h3>
   <p>Our mission is to amplify students' lives with a tangible relationship with Christ.</p>
   <p>Through authentic fellowship and a firm foundation in truth, our goal is for students to be transformed and to exemplify Christ 
    like character.</p>
   <p>Amplify: relationship, fellowship, knowledge and character.</p>
   <p>Exemplify: character, service, leadership and obedience. </p>  	
   <h3> Cedar Run Community Church</h3>
   <p>to find out more about the church itself please click<a href="http://www.cedarrun.net">here</a></p>      
{% endblock %}

website/templates/general/believe.html
{% extends 'base.html' %}
{% block title %}What We Believe{% endblock %}
{% block pagetitle %}What we believe{% endblock %}
{% block content %}
  <h2>The Holy Bible</h2>
  <p>The sole basis for our belief is the Bible (the Scriptures of the Old and New Testaments). We believe it to be uniquely God-inspired and 
inerrant in the original writings. This means that all facts (i.e., theological, doctrinal, historical, numerical, chronological, scientific, 
etc.) that the Bible intends to affirm are exempt from error in whole and in part. The Scriptures are the supreme and final authority in faith 
and life. (II Timothy 3:16; II Peter 1:21)</p>
 
 
<h2>God</h2>
 
<p>We believe in one God, who is creator and sustainer of life, eternally existing in three persons: Father, Son and Holy Spirit; each of whom is 
equal in power and glory. (Matt. 3:16, 17; Matt. 28:19; I Pet. 1:2)</p>
 
 
<h3>The Father</h3>
 
<p>We believe in God the Father, the first person of the Trinity. He transcends human description and natural laws because He is greater than them. 
(Gen. 1:1; Ex. 3:14; Ex. 34:6, 7; John 5:19-23)</p>
 
 
<h3>Jesus Christ</h3>
 
<p>We believe that Jesus Christ was conceived by the Holy Spirit and born of the virgin Mary and is True God and True Man. (Isaiah 7:14; John 
1:1-14; John 5:18; Phil. 2:6-ll)
 
We believe in the bodily death and resurrection of Christ, in His ascension into heaven where He is seated at the right hand of God, and in His 
ministry for us as High Priest and Advocate. (Luke 24:50-52; I Corinthians 15:3,4)
 
He shall come again to earth, personally and visibly, to consummate history and the eternal plan of God. (Titus 2:13; Acts 1:11)</p>
 
 
<h3>Holy Spirit</h3>
 
<p>We believe the Holy Spirit was sent into the world by the Father and the Son to impart to mankind the saving work of Christ. He convicts 
sinners, awakens in them a recognition of their need of a Savior and regenerates them. At the point of salvation He permanently indwells every 
believer to become the source of assurance, strength and wisdom, and uniquely endows each believer with gifts for building up the Church. The 
Holy Spirit guides believers in understanding and applying the Scripture. His power and control are appropriated by faith, making it possible 
for the believer to lead a life of Christ like character and to bear fruit to the glory of the Father. (John 16:8-11; Rom. 8:16-27; 1 
Corinthians 12:7; Titus 3:5; 1 Peter 4:10)</p>
 

<h2>Mankind</h2>
 
<p>We believe that mankind was created directly by God (we are not the product of an evolutionary process) in the image of God.  As a result of 
Adam's sin, all of humanity inherited a sin nature and thereby incurred not only physical death, but also spiritual death which is 
separation from God. Mankind is unable to remedy this situation by his own efforts. (Gen. 1:27; 2:17; 3:6; Rom. 5:12-19; Rom. 3:10-12, 23; Rom. 
6:23)</p>
 

<h2>Satan</h2>
 
<p>We acknowledge the existence of Satan created as an angel, though now fallen and the leader of all the demonic powers. He is opposed to 
God and constantly attempting to disrupt God's work and damage God's people. His final destiny is eternal justice in the lake of fire. 
(1 Peter 5:8; Matthew 25:41; Revelation 20:10)</p>
 

<h2>Salvation</h2>
 
<p>We believe that the Lord Jesus Christ is the only way for mankind to be reconciled to God.  He died for our sins according to the Scriptures as 
a substitutionary sacrifice and that all who believe in Him are justified on the grounds of His death and resurrection. (Romans 4:24, 25; John 
14:6; I Corinthians 15:3; I John 1:7; Acts 13:39; II Corinthians 5:21; I Peter 2:24)
 
We believe that all who receive Christ by faith are born again of the Holy Spirit and thereby become the children of God. (John 1:12; 3:16; 
3:5-7; Rom. 8:4; 10:9, 10; Gal. 3:26)
 
We believe in righteous living and good works, not as the means of salvation, but as its evidence and fruit. (Ephesians 2:8-10; Romans 6:1,2; 
Romans 12:1,2; 1 John 3:9,10)
 
We believe in the eternal salvation of the believer, i.e. that it is not possible for the true child of God to lose his salvation (John 
10:27-29; Romans 8:35; Ephesians 1:13, 14; Philippians 1:6; 1 Peter 1:5)
 
We believe in the bodily resurrection of the dead to eternal life for those who have received Christ as Savior and Lord and to eternal 
separation from God for those who have not. (John 5:28,29)</p>
 
 
<h2>The Church</h2>
 
<p>We believe in the one true Church, universal, a living spiritual body, of which Christ is the Head, and of which all who have received Christ as 
Savior and Lord are members. We believe that a visible Church is a local body of believers in Jesus Christ, whose purpose is to gather together 
for exaltation, edification, evangelism and extension. (Ephesians 5:20-32)  
 
The members of the Church should seek to discover and exercise their spiritual gifts in useful forms of ministry. We believe that the Church is 
salt and light resulting in a Christ-like influence in the world. (Matthew 5:13, 14)</p>
 
 
<h2>Baptism</h2>
 
<p>We believe that baptism was ordained by our Lord Jesus Christ and that the scriptures direct that every believer be baptized. We believe that 
baptism is symbolic of the inner transformation occurring the moment a person receives Christ. We believe that baptism as a statement of one 
spiritual baptism in Christ must come after the person receives Christ. (Matthew 28:18-20; Romans 6:1-13)</p>
 
 
<h2>The Lord's Supper</h2>
 
<p>We believe that the Lord's Supper serves to remind us in symbolic manner of the death of the Lord Jesus Christ on our behalf. This ordinance is 
for those who have received Christ as Savior and Lord. (I Corinthians 11:26)</p>
 
 
<h2>Faith and Practice</h2>
 
<p>We believe that Scripture is the final authority in all matters of faith and practice. This Church recognizes that it cannot bind the conscience 
of individual members in areas where Scripture is silent. Rather, each believer is to be led in those areas by the Lord, to whom he or she alone 
is ultimately responsible. (Romans 14)
 
We believe this Statement of Beliefs to be an accurate summary of what Scripture teaches. All members shall refrain from advocating doctrines 
that are not included in this Statement of Beliefs in such a way as to cause dissension. (I Timothy 3)</p>
{% endblock %}

website/templates/general/calendar.html
{% extends 'base.html' %}
{% block title %}Calendar{% endblock %}
{% block pagetitle %}Calendar{% endblock %}
{% block content %}
<object data="https://calendar.google.com/calendar/embed?src=crccreverb%40gmail.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
</object>
{% endblock %}

website/templates/general/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock %}
{% block pagetitle %}Contact{% endblock %}
{% block content %}
   <h3> Call us</h3>
   <p>703-796-3535</p> 
   <h3>Email</h3>
   <p>CRCCReverb@gmail.com</p>
   <h3>Address</h3>
   <p>Cedar Run Community Church
   13560 MCLearen Rd Herndon, VA 20171</p>  	
{% endblock %}

website/templates/general/index.html
{% extends 'blog/base.html' %}
{% block title %}CRCC Reverb{% endblock %}
{% block pagetitle %}Reverb{% endblock %}
{% block content %}
<h2>Welcome!</h2>
<p>Whether you've wandered to our site on accident or ventured with a purpose, we're glad you're here! If you're looking for a fun 
environment to make new friends and grow in your relationship with Jesus, or need a secure place to seek answers, look no further. At 
Cedar Run youth, we challenge students to enlarge their hearts for Jesus and cultivate a desire for his Word in a relaxed and loving 
atmosphere. We would love for you to come join us!</p>

<div class="well">
<p>Colossians 1:10 "so that you will walk in a manner worthy of the Lord, to please Him in all respects, bearing fruit in every good
work and increasing in the knowledge of God;"
</div>

{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item disabled" href="#">Browse {{ section }} archives</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>

{% endif %}

{% endblock %}

website/templates/general/pictures.html
{% extends 'base.html' %}
{% block title %}Pictures{% endblock %}
{% block pagetitle %}Pictures{% endblock %}
{% block content %}
<h3><a href="https://goo.gl/photos/3Cv6QusFzpW8Xd7k6">Summer 2016</a></h3>
<h3><a href="https://goo.gl/photos/Akzh9wM1BdZewZk48">2016/2017</a></h3>
{% endblock %}

website/templates/general/team.html
{% extends 'base.html' %}
{% block title %}Team{% endblock %}
{% block pagetitle %}Team{% endblock %}
{% block content %}
<div class="well">
   <h3> Travis Hughlett</h3>
   <p>Youth Director</p> 
   <p>Travis has been married for 3 years to his beautiful wife Kelsey, and has lived in Northern Virginia his whole life. 
      He graduated Liberty University in 2011 with a degree in Youth Ministry with a specialization in Biblical Studies.
      His desire to lead youth with the truth of the gospel started when he was 18, and he stoped fighting the call God had on his life.
      Over the next 4 years he held different internships until he landed back here in his home town at Cedar Run. 
      In his free time you can find him either at the gym, hanging out with friends, or putting some time in on the Xbox. 
      When he does read he enjoys books from Francis Chan such as, "You and Me forever", and "Crazy Love". His life has been one huge 
      lesson from God, teaching, refining, and building what He wants for Travis, he is just along for the ride.</p>
</div>
<div class="well">
   <h3>Sarah Shirey</h3>
   <p>Associate Youth Director</p>
   <p>Previously working in media & television, Sarah was called to fulltime ministry back in the fall of 2012. She is an avid coffee 
drinker, cheese aficionado, Star Wars enthusiast and lover of all things furry. She loves how all of scripture is connected and 
enjoys studying exegesis and etymology . Her desire is to cultivate an understanding of the Word with students and to ignite their 
passion for the Lord and his law.</p>
</div>
<div class="well">
   <h3>Siebren (viking) Bakker</h3>
   <p>Volunteer</p>
<p>Siebren is a nerd. He especially loves gaming in all its forms, and reading. He loves how stories and games bring people 
together and really connect to each other. He started volunteering in the spring of 2016 working the soundboard. It didn’t take 
him long to start helping out with group discussions and events. He desires to be a person the youth can trust and turn to, and he 
hopes to see them grow as individuals, and in their faith.</p>
</div>
<div class="well">
<h3>Christina Garcia-Bakker</h3>
<p>Volunteer</p>
<p>Born in Illinois raised in Holland she love to travel. From the people she meets, the creations she sees, and the historical place 
she experiences, she loves connecting it all back to God. She does the same with all her creative endeavors, and while enjoying the 
art and stories from others, she loves to bring it all back to God, how holy and good He is, and how broken we are. She loves the 
Lord and really wants to awaken the Love for Him in the hearts of the students, in the hope they will serve Him with joy, love, and 
thanksgiving</p>
</div>
<div class="well">
<h3>Austin Shirey</h3>
<p>Volunteer</p>
<p>Austin Shirey is Sarah's husband - a role he firmly believes is the greatest in the world! Austin loves anything that has to do 
with fantasy, superheroes, science fiction, video games, music and movies; he's actually currently writing his own fantasy novels in 
his spare time. When he's not being nerdy, he loves serving alongside his "nerd mate" Sarah and volunteering with the youth group. He 
desires to have the youth experience the gospel freedom Jesus offers and to instill a love of God's Word in their hearts, that they 
might be young men and women who "seek the Lord continually" (Psalm 105:4)</p>
</div>
<div class="well">
<h3>Chelsea Tekesky</h3>
<p>Volunteer</p>
<p>Chelsea Tekesky grew up in Herndon and attended Trinity Christian School. It was at Trinity that she came to know and love 
Jesus Christ. She went to college at Christopher Newport University. During this time, she met her husband Scott. Chelsea loves 
animals, traveling, and being outside. She is passionate about serving with the Senior High and sharing the beautiful love of Jesus
with the students.</p>
</div>
<div class="well">
<h3>Scott Tekesky</h3>
<p>Volunteer</p>
</div>  	
{% endblock %}

website/templates/layouts/header.html
<!-- Bootstrap Navbar -->
  <header>
    <nav class="navbar navbar-inverse">

      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CRCC Reverb</a>
        </div>

        <div class="collapse navbar-collapse navbar-left" id="myNavbar">
          <ul class="nav navbar-nav">
            <li {{is_active('pages.all_pages')}}><a href="{{ url_for('pages.all_pages') }}">Home</a></li>
            <li class="dropdown ">
              <a class="dropdown" href="{{ url_for('general.about') }}">About<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li {{is_active('general.team') }}><a href="{{ url_for('general.team') }}">Team</a></li>
                <li {{is_active('general.believe') }}><a href="{{ url_for('general.believe') }}">What We Believe</a></li>
                <li {{is_active('general.contact')}}><a href="{{ url_for('general.contact') }}">Contact</a></li>
              </ul>
            </li> 
            <li {{is_active('general.calendar')}}><a href="{{ url_for('general.calendar') }}">Calendar</a></li>
            <li {{is_active('general.pictures')}}><a href="{{ url_for('general.pictures') }}">Pictures</a></li>
            <li><a href="http://throwdown.crccreverb.com">Throwdown</a></li>
          </ul>
        </div> 


        <!-- Social Media Buttons -->
        <div class="collapse navbar-collapse navbar-right" id="mySocial">
          <ul class="nav navbar-nav navbar-right social">
            <li><a class="fa fa-book fa-lg" href="https://library.crccreverb.com" target="_blank"></a></li>
            <li><a class="fa fa-instagram fa-lg" href="https://www.instagram.com/crcc_reverb" target="_blank"></a></li>
            <li><a class="fa fa-twitter fa-lg" href="https://www.twitter.com/crcc_reverb" target="_blank"></a></li>
          </ul>
        </div>
  
      </div>

    </nav>
  </header>